### ISSUE TITLE
Editing

### ISSUE THREAD

**Issue by DominicNr2** [OFHansen/JHotDraw-group6#4]
As a user i, want the basic editing tools, so that i can edit my figures.

**Comment by DominicNr2** [comment]
Child Issue #1
As a user, I want to use the cut function on the figures i have created, so that i can cut the figure to my clipboard.

**Comment by DominicNr2** [comment]
Child Issue #2
As a user, I want a copy function to copy my figure, so that i can create identical figures.

**Comment by DominicNr2** [comment]
Child Issue #3
As a user, I want paste function, so that i can paste the figures i have in my clipboard.

**Comment by DominicNr2** [comment]
Child Issue #4
As a user, I want a delete function, so that i can delete any figures i don't want on my panel.

**Comment by DominicNr2** [comment]
Child Issue
As a user, I want a duplicate function, so i don't have to use both the copy and paste function, when i need to duplicate a figure.

**Comment by OFHansen** [comment]
Dominic you are linking the other active issues by typing #<number>
